### ISSUE TITLE
[Suggestion] Handle HTTP Request/Response Async

### ISSUE THREAD

**Issue by BlackBeltPanda** [NamelessMC/Nameless-Plugin#1]
In case a HTTP response isn't received immediately, the HTTP request and response should be handled async to prevent locking the main thread. =)

**Comment by samerton** [comment]
Thanks for the suggestion!
I had this in mind whilst implementing the API connection, currently the request is handled async ([here](https://github.com/NamelessMC/Nameless-Plugin/blob/master/com/namelessmc/namelessplugin/RegisterCommand.java#L34)).
I'm very new to Java, so there may be something I'm doing wrong however.

**Comment by BlackBeltPanda** [comment]
Was that there before? My eyes must have glanced right by it. XD
But yeah, that looks good. =)
