### ISSUE TITLE
Plugin Based Status Page

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless-Plugin#101]
I really want my status page to be like this
https://tensa.co.ua/status/ (also see attached image)
But I cannot do that the way my network is setup

Is it possible that a feature could be added that makes the ping work with the nameless plugin?
I am thinking of a system similar to push notifications.
When the status page is visited it sends a request to the plugin, and the plugin responds with online players. If no response is received then the site says the server is offline.

Link to other github issue: https://github.com/NamelessMC/Nameless/issues/2017

![image](https://user-images.githubusercontent.com/10292779/103243244-42e83b00-4927-11eb-91db-9b66fb16a04a.png)

**Comment by samerton** [comment]
This is already possible from a plugin side of view as it sends data from each server over at a set interval, just needs some work on the web side of things

**Comment by StormyIceLeopard** [comment]
So it already sends players online? The names and the heads?

**Comment by Derkades** [comment]
It does send online players and their UUIDs (which the website can use to display heads).

It also sends ranks, vault balance, world position, playtime and has the option to send any PlaceholderAPI placeholder.
