### ISSUE TITLE
Wrong param name for userInfo

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless-Plugin#104]
I ran `/info` ingame, and this was in my log (debug enabled)
```
[19:50:22 INFO]: Making connection GET to url https://nmc.tadhgboyle.dev/index.php?route=/api/v2/**API_KEY_REMOVED**/userInfo&username=9490b898-856a-4aae-8de3-2986d007269b
```
The param used was "username", not "uuid"

**Comment by Derkades** [comment]
Did you run /info with a UUID or username? Also, were you running the absolute latest version of the plugin? I changed how the /info command worked recently.

**Comment by Aberdeener** [comment]
Just typed /info, no args in chat. Using latest from the CI

**Comment by Derkades** [comment]
Ah yes, without args was the issue
