### ISSUE TITLE
[Suggestion] drone.io Integration

### ISSUE THREAD

**Issue by Lmmb74** [NamelessMC/Nameless-Plugin#11]
@samerton You are the only one with the account to allow this. This way we can ensure every commit is buildable, and drone.io will actually throw the errors ;).

**Comment by IsS127** [comment]
Do you mean something like Jenkins?

**Comment by Lmmb74** [comment]
drone.io is just continuous integration checking like Jenkins. But if @samerton actually sets up a Jenkins build server, that would be awesome.

**Comment by IsS127** [comment]
I asked @samerton and Jenkins is up :)

**Comment by Lmmb74** [comment]
:DDDDDD. Then close this and gimme the link plsss. Also set up some users for Samerton, you and me, since we are the main contributors.

**Comment by IsS127** [comment]
I will share it soon for the public.

**Comment by Lmmb74** [comment]
:D

**Comment by IsS127** [comment]
@Lmmb74,
Do you have skype?

**Comment by Lmmb74** [comment]
Yup. It's just like my username :)

**Comment by IsS127** [comment]
Closing This because there is jenkins now
