### ISSUE TITLE
[Suggestion] SpongeAPI Support

### ISSUE THREAD

**Issue by Lmmb74** [NamelessMC/Nameless-Plugin#12]
I am working on a Sponge update. I will make a pull request when it's finished ;)

**Comment by Lmmb74** [comment]
- [ ]  Main Sponge Support
- [ ]  Config Fixes

**Comment by Lmmb74** [comment]
The main trouble I am getting is having the config done u.u. Since the config has many comments, I am thinking of including the nameless.conf in the jar file.

**Comment by Lmmb74** [comment]
Welp, the commands are my main trouble right now. I have not still managed to get succesfully the arguments. If you want to check, pls do it.

**Comment by Lmmb74** [comment]
Could you check if you can help me with the commands in the sponge plugin? Cause I get a NullPointerException everytime I try to get the api url from the config.

**Comment by samerton** [comment]
Sure, I'll try to check it out either tonight or tomorrow.

**Comment by Lmmb74** [comment]
Kk :)

**Comment by Lmmb74** [comment]
@IsS127 @samerton The only thing I have to fix in my fork is getting the api-url string. After that I will make the pull request. Please help me

**Comment by IsS127** [comment]
Ive never really worked with Sponge..
But ill check it out.

**Comment by Lmmb74** [comment]
Ok. Me neither, I am learning from its javadocs xD. I thought it would be more similar to bukkit u.u

**Comment by IsS127** [comment]
Check this out then :) https://docs.spongepowered.org/master/en/plugin/configuration/nodes.html

**Comment by Lmmb74** [comment]
Maybe I should use a YAMLConfigurationLoader instead of HOCON one (which is a system I never used)

**Comment by Lmmb74** [comment]
Also, the path to the nodes I used with the HOCON system was right ("api-url" & "enable-report"). I followed the syntax. I even checked how it was generated in a plugin I made for testing.

**Comment by Lmmb74** [comment]
Nope, same error even with YAMLConfigurationLoader u.u

**Comment by Lmmb74** [comment]
To be more specific, this is the code I do not get to work:
`NamelessPlugin.getInstance().getAPIUrl().isEmpty()`
It is located in every command class when api url is checked.

**Comment by Lmmb74** [comment]
Any idea?

**Comment by IsS127** [comment]
NamelessPlugin.getInstance().getAPIUrl().isEmpty()? are u trying to check if its empty?

**Comment by Lmmb74** [comment]
Yup. So if it is empty, then it is needed to be set.

**Comment by IsS127** [comment]
try NamelessPlugin.getInstance().getAPIUrl() == null

**Comment by Lmmb74** [comment]
Kk

**Comment by Lmmb74** [comment]
Nope:

> [19:46:47] [Server thread/INFO]: Error occurred while executing command: null
[19:46:47] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'getuser Lmmb74' for source DedicatedServer: null
java.lang.NullPointerException
        at com.namelessmc.namelessplugin.sponge.commands.GetUserCommand.execute(GetUserCommand.java:37) ~[GetUserCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2171-5.1.0-BETA-1992]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-1992]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-1992]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Lmmb74** [comment]
Line 37:
`if(NamelessPlugin.getInstance().getAPIUrl() == null){`

**Comment by IsS127** [comment]
Ok, try getting it from config and check if empty.

**Comment by Lmmb74** [comment]
Like before?

**Comment by IsS127** [comment]
Oh.. Does it store the apiurl in the apiURL string?

**Comment by Lmmb74** [comment]
Yup. In the main file. I just made a debug test and it seems to work. But when the command try to get it, it does not work.

**Comment by IsS127** [comment]
wait where are you trying to do the apirul check?

**Comment by Lmmb74** [comment]
The check is in the command executor, but the api url is set in the main file (NamelessPlugin.java).

**Comment by IsS127** [comment]
try to do the check on the Initialize in the main file.
like in the spigot version
https://github.com/NamelessMC/Nameless-Plugin/blob/master/nameless-spigot/src/main/java/com/namelessmc/namelessplugin/spigot/NamelessPlugin.java#L170-L175

**Comment by Lmmb74** [comment]
Ok, but since Sponge has no option to disable the plugin, I will just make it that if the plugin finds and api url, it will register commands :).

**Comment by IsS127** [comment]
Bungeecord didn't have that either.
So do what I did to the bungeecord

 https://github.com/NamelessMC/Nameless-Plugin/blob/master/nameless-bungee/src/main/java/com/namelessmc/namelessplugin/bungeecord/NamelessPlugin.java#L134-L138

then I check if its true when I use the apiURl.

**Comment by Lmmb74** [comment]
I am using the apiUrl.isEmpty() instead of (plugin.hasSetUrl == false)

**Comment by Lmmb74** [comment]
Also, I made the whole check in the main plugin file

**Comment by IsS127** [comment]
Ok :)

**Comment by Lmmb74** [comment]
https://github.com/Lmmb74/Nameless-Plugin/commit/77976471aaead4f7ebfb22521292b4ada11cd30c
Just pushed the checks for you to see ;)

**Comment by Lmmb74** [comment]
But the problem keeps happening:
> Error occurred while executing command 'getuser Lmmb74' for source DedicatedServer: null
java.lang.NullPointerException

**Comment by Lmmb74** [comment]
I have done everything but fixing the commands u.u

**Comment by Lmmb74** [comment]
I am getting out of ideas. I searched for anything similar in the forums but I cannot get this to work...

**Comment by IsS127** [comment]
I don't really know why this is happening.

**Comment by Lmmb74** [comment]
Me neither u.u

**Comment by Lmmb74** [comment]
But I will not give up :D

**Comment by samerton** [comment]
Were you able to resolve this issue @Lmmb74?

**Comment by Lmmb74** [comment]
YEAH :DDDD
