### ISSUE TITLE
[Question] Maven?

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless-Plugin#14]
The Maven update,
What is maven exactly.
And doesn't that do so bungee, spigot and so on is in sepperate jars?
Because its supposed to be in 1 jar :)

**Comment by Lmmb74** [comment]
Maven is a compiler software based in xml configuration parameters. I made it so every module is compiled in its very own jar, but also every module is shaded into one jar as said in README.md.

**Comment by samerton** [comment]
I'll mark this as closed :)
