### ISSUE TITLE
Option to whitelist users with specific group instead of all registered users

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless-Plugin#166]

**Comment by Slddev** [comment]
This still isn't added? Would really like this feature

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/issues/2462

**Comment by Slddev** [comment]
> [NamelessMC/Nameless#2462](https://github.com/NamelessMC/Nameless/issues/2462)

Yeah its added right? I mean the issue has been closed and has been added to the Java API.

**Comment by Derkades** [comment]
It will be added in pr13

**Comment by Slddev** [comment]
> It will be added in pr13

Oh ok.
