### ISSUE TITLE
Option to whitelist users by name instead of UUID.

### ISSUE THREAD

**Issue by Slddev** [NamelessMC/Nameless-Plugin#172]
This option is useful for cracked Minecraft Accounts.

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless-Plugin/commit/e6ea4e614a4fb0e6c0cf0a464d734a8d68655b9a

**Comment by Slddev** [comment]
> [e6ea4e6](https://github.com/NamelessMC/Nameless-Plugin/commit/e6ea4e614a4fb0e6c0cf0a464d734a8d68655b9a)

The plugin on spigot has not been updated.

**Comment by Derkades** [comment]
Thanks, I'll update it. Did you know there are precompiled beta builds available as well? https://ci.rkslot.nl/view/NamelessMC/
