### ISSUE TITLE
Ignore UUIDs doesn't work

### ISSUE THREAD

**Issue by Slddev** [NamelessMC/Nameless-Plugin#175]
Ignore UUIDs in the config.yml doesn't work. I added a UUID in that space and reloaded the plugin. Whitelisted a player with that UUID and the plugin keeps removing it.

**Comment by Derkades** [comment]
Are you sure it's the correct UUID? Note the difference between mojang uuids and offline uuids. Please confirm by enabling logging.

**Comment by Derkades** [comment]
For your convenience, it now uses usernames instead of uuids when api-usernames is enabled: 9b7d89a61894f9ca0a720151d4cb0b5df6cec40e
