### ISSUE TITLE
Cannot read config.yml

### ISSUE THREAD

**Issue by Slddev** [NamelessMC/Nameless-Plugin#182]
Checked everything, permissions, name, etc. It just refuses to read config.yml. Tried using a fresh config, didn't work either.

**Comment by Derkades** [comment]
What does "refuses to read" mean?

**Comment by Slddev** [comment]
> What does "refuses to read" mean?

It gives an error on startup saying that it cannot read /plugins/NamelessMC/config.yml.

**Comment by Slddev** [comment]
Tried to turn on debug mode too, but since it can't read config.yml, it doesn't turn on.

**Comment by Slddev** [comment]
Nevermind, I fixed it but now I have a new problem. It doesn't whitelist the players now. I have the right API url, I set everything right in the config. It is saying the right things but it doesn't whitelist the users.

**Comment by PikaMug** [comment]
The update notes say you should reset the file if you use whitelist sync:
https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032/update?update=427088

**Comment by Slddev** [comment]
> The update notes say you should reset the file if you use whitelist sync: https://www.spigotmc.org/resources/nameless-plugin-for-v2.59032/update?update=427088

Read my first message. "Tried using a fresh config, didn't work either."

**Comment by PikaMug** [comment]
I did read that, but since you didn't explain how you "fixed it" all I can really do is point that.
