### ISSUE TITLE
[Suggestion] Custom Messages

### ISSUE THREAD

**Issue by Lmmb74** [NamelessMC/Nameless-Plugin#22]
I will work today on a MessagesUtil for custom messages ;).

**Comment by Lmmb74** [comment]
Progress:
https://github.com/NamelessMC/Nameless-Plugin/commit/a53531a4292b0cec61c4b8d3bd404f56afbd1e8f

**Comment by Envici** [comment]
👍

**Comment by IsS127** [comment]
This is done for the bungeecord version that I will push sooner  :)

**Comment by IsS127** [comment]
https://github.com/NamelessMC/Nameless-Plugin/commit/26de1f213cfeae0800d5922232031ac13b55c884

**Comment by IsS127** [comment]
Im closing this now cus its basicly done.
