### ISSUE TITLE
Console Error upon a player joining

### ISSUE THREAD

**Issue by Liphius** [NamelessMC/Nameless-Plugin#25]
This error sometimes appears when a player joins the server:

`31.12 13:36:38 [Server] WARN at java.lang.Thread.run(Unknown Source)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
31.12 13:36:38 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327)
31.12 13:36:38 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
31.12 13:36:38 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
31.12 13:36:38 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
31.12 13:36:38 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
31.12 13:36:38 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
31.12 13:36:38 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
31.12 13:36:38 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
31.12 13:36:38 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
31.12 13:36:38 [Server] WARN at com.namelessmc.namelessplugin.spigot.player.PlayerEventListener.onPlayerJoin(PlayerEventListener.java:39)
31.12 13:36:38 [Server] WARN at com.namelessmc.namelessplugin.spigot.player.PlayerEventListener.userGetNotification(PlayerEventListener.java:52)
31.12 13:36:38 [Server] WARN at com.namelessmc.namelessplugin.spigot.utils.RequestUtil.getNotifications(RequestUtil.java:256)
31.12 13:36:38 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
31.12 13:36:38 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
31.12 13:36:38 [Server] WARN at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
31.12 13:36:38 [Server] WARN at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
31.12 13:36:38 [Server] WARN at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
31.12 13:36:38 [Server] WARN Unexpected character (C) at position 0.`

**Comment by IsS127** [comment]
What Minecraft software?

**Comment by Lmmb74** [comment]
Spigot :P. Gonna check now ;)

**Comment by IsS127** [comment]
We will be fixing bugs this week coming :)

**Comment by Lmmb74** [comment]
Yup :D

**Comment by Liphius** [comment]
Any progress on this issue?

**Comment by samerton** [comment]
I'll take a look into it shortly @Liphius :)

**Comment by IsS127** [comment]
Yes there has been progress in this

**Comment by IsS127** [comment]
Im almost done with this issue.

**Comment by IsS127** [comment]
Fixed
