### ISSUE TITLE
Registrations through minecraft server only

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless-Plugin#26]
When is your plugin comming?
Idea to add an option on the website to enable only registrations thru the minecraft server, and that when they first login they will be asked to complete there profile settings like age etc.
or even with an in-game GUI.

**Comment by samerton** [comment]
This is currently possible in the latest release of Nameless, as site registration can be disabled within the AdminCP -> Core -> Modules -> Registration tab.

As for the plugin, it's still a work in progress however hopefully it's not far away from an initial release.

**Comment by dangerORclose** [comment]
Fast reply,
I knew that that was possible, but then there is no redirection to a page telling you you can only registrer from in-game. It just redirects you to the homepage.

**Comment by samerton** [comment]
Ah I see, I can get that implemented for the full plugin release.

**Comment by IsS127** [comment]
For the plugin, there will be  pre-release this month HOPEFULLY.
And for the ingame-gui. it might be possible.

**Comment by Derkades** [comment]
I can work on a GUI, I already have an API for creating menus so that should be pretty easy. The gui will only display icons the player has permission for. Command to open the gui configurable.
