### ISSUE TITLE
[BUG] Config file

### ISSUE THREAD

**Issue by dangerORclose** [NamelessMC/Nameless-Plugin#27]
Hey, i saw this. Sounds like theres something wrong, or just the message, or a configuration by you :/ http://prntscr.com/dqd74b

**Comment by IsS127** [comment]
Please specify some more information..

**Comment by dangerORclose** [comment]
XD well some are empty, but on pm it says alerts  and on alerts it says pms. 
I'm not good with English, but that looks me weird. No? I may be wrong. :)

**Comment by IsS127** [comment]
What server software?

**Comment by dangerORclose** [comment]
Sorry, Spigot. Latest version.

**Comment by IsS127** [comment]
Thanks, There Will be update soon that fixes the bug :)

**Comment by Fellings1** [comment]
@IsS127 Any progress regarding this?

**Comment by IsS127** [comment]
Yes, but not done yet :) this bug is currently for spigot and sponge. The plugin should work fine with bungeecord.

**Comment by IsS127** [comment]
I Will post an update with the New api for spigot & sponge

**Comment by Fellings1** [comment]
@IsS127 Thanks

**Comment by IsS127** [comment]
Fixed
