### ISSUE TITLE
[Suggestion] Bans/Sync

### ISSUE THREAD

**Issue by DoraKlikOpDora** [NamelessMC/Nameless-Plugin#28]
Since Nameless site has a complete and semi-advanced bansystem in it, why not add a bansystem in Namelessplugin?
Bansystem is an addon in nameless, but you have to use BAT or any other banplugin. Almost everybody will use the bansystem, so why not add it in the basic plugin to have it integrated the full 100%?

Besides of that: Group sync for as well BungeeCord as Spigot. BungeeCord will be usefull to give players certain permissions based on their group (instead of manually adding a player to a group and having to restart/reload everything). For Spigot it is a solution to sync ranks for Donators and give them a private form or something on the website.

**Comment by IsS127** [comment]
There is a group sync.

**Comment by IsS127** [comment]
Also there is a group sync. 
It sets the group on the website.
We could do set group on the server too.
The Ban system hopefully comes in 1.1. But the group sync will come in 1.0 (First release)

**Comment by joshwenke** [comment]
Could you do the same permission thing you use for groups right now? If a user has a certain permission they're in a certain group, and you could make it so if a user has a certain permission in-game, they're banned from the website as well.

**Comment by Slddev** [comment]
bump, I want this feature.
