### ISSUE TITLE
Reorganizing the API

### ISSUE THREAD

**Issue by Maximvdw** [NamelessMC/Nameless-Plugin#29]
I recommend reorganizing the API into modules.

>Nameless-API
>> Nameless-Spigot
>> Nameless-Sponge
>> Nameless-BungeeCord

Basically. the API remains the same... you have HTTP calls ,etc.. the only reason you have these sub modules  are because you are using metrics or methods that take in a player object.

I recommend creating a main module API containing only the API and creating submodules extending the main module.

PS: Also, do not use "API" as a package name (keep java convention and make it lowercase)

**Comment by IsS127** [comment]
That is not the api repo. That is the plugin itself. But thx

**Comment by Maximvdw** [comment]
Uh, I could've sworn I clicked on the API repo. sry

**Comment by IsS127** [comment]
But the plugin contains the api.

**Comment by Maximvdw** [comment]
I know, but you don't always want the user to use a plugin. Especially when its not a minecraft plugin

**Comment by IsS127** [comment]
We Are gonna make a api plugin/library alone.
