### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless-Plugin#3]
Hey, if u need any help with the plugin,
I can help :)

**Comment by samerton** [comment]
Thanks for the offer! 
Any contributions towards the plugin development would be greatly appreciated, please feel free to submit any changes you'd like to see within the code. We have a to-do list [here](https://github.com/NamelessMC/Nameless-Plugin/wiki/To-Do), which includes the features which need tackling next.

**Comment by IsS127** [comment]
Do you have skype?

**Comment by samerton** [comment]
There's a Nameless Discord chat available [here](https://discord.gg/r7Eq4jw) :)

**Comment by IsS127** [comment]
Pull requested some changes.

**Comment by IsS127** [comment]
and im almost done with a new getuser command.

**Comment by samerton** [comment]
I'll mark this issue as closed :)
