### ISSUE TITLE
[Bug/Suggestion] Conflicting Commands

### ISSUE THREAD

**Issue by MuhsinunCool** [NamelessMC/Nameless-Plugin#30]
* What kind of issue is it (Question, Bug, Suggestion, etc)? Bug/Suggestion

* In which Minecraft Server Software did this occur? 1.11

* In which Build of NamelessMC Plugin did it occur [Send link + Build number]? Current (1.0.15 NMC)

* How would you describe the issue?

The commands of this plugin conflict with those of other plugins. For example, the /register command would conflict with the commands of a server register & login plugin. I would suggest that u make a main command; /namelessmc with the alias of /nmc and THEN the rest of the command. So for example, /register for this plugin would become /nmc register.

Another way to tackle this issue would be to add a file with config options that allow you to change the commands, including with arguments. So for example, the default entry for the forum registration could be /register. Then, the server admin could change the config entry for the forum registration command to be /nmc register or /registerf. By "including with arguments" I mean allowing the use of arguments in the changed command. So if the default entry is /register, it can be changed to /nmc registerforums, or similar.

* Do you have (relevant) resources about this issue (Logs, pictures, etc.)? No

**Comment by IsS127** [comment]
This Will be added and Its under progress. What mc server software is This?

**Comment by MuhsinunCool** [comment]
Spigot, & thanks! It would be nice if it was added to all the versions b/c all of them can have the same problem. <3 :D

**Comment by IsS127** [comment]
Hmm for spigot it might be hard.. because spigot has a plugin.yml and in that u contain the commands
But ive seen plugins do it without plugin.yml.
I will see what I can do for spigot :)

**Comment by MuhsinunCool** [comment]
@IsS127 Thanks! :D So will it work for the other platforms tho? Also, can't u like make a variable that reads the config like: config.yml then commands.forumsregister then echo the value of that variable into where the plugin declares that specific command?

**Comment by Fellings1** [comment]
@MuhsinunCool I believe so, but I think @IsS127 should confirm.

**Comment by IsS127** [comment]
It Will work with bungeecord and sponge. With spigot i am not sure. I Will figure something out as i said.

**Comment by Camouflage100** [comment]
Can't be done in Spigot w/o distributing alternate files that contain different plugin.ymls'

**Comment by IsS127** [comment]
I've already done it.

**Comment by IsS127** [comment]
Closed because it's done for bungee cord too but not pushed yet.

**Comment by MuhsinunCool** [comment]
Alr so it works on BungeeCord and Spigot?

**Comment by IsS127** [comment]
Works with spigot atm with only single commands.
Will be pushing a feature like this: "/command <subcommand>" for spigot next week
And for bungeecord ill be doing next week too.

**Comment by Derkades** [comment]
Do you need info on how to create custom commands on the fly without putting them in plugin.yml? Because I know how

**Comment by IsS127** [comment]
Forgot to close, This is done.
