### ISSUE TITLE
Possibility to set a different date and time format

### ISSUE THREAD

**Issue by DoreK333** [NamelessMC/Nameless-Plugin#304]
I suggest to add the option to change the date and time format to another.

**Comment by Derkades** [comment]
This is already possible using `datetime-format` in `main.yaml`

**Comment by DoreK333** [comment]
But in /userinfo command i see another format 🤷 
![image](https://user-images.githubusercontent.com/11007700/199295649-6b1e7559-d016-4cac-93db-bf7001e9c1a5.png)

**Comment by Derkades** [comment]
you have found a bug! should be fixed now
