### ISSUE TITLE
NamelessMC HttpHeadersTimeoutException stalls Waterfall-Server CPU

### ISSUE THREAD

**Issue by Whitescan** [NamelessMC/Nameless-Plugin#325]
Hello, although the issue itself may occure due to networking issues the plugin should not get stuck in trying over and over again until CPU hits the maximum and stalls the entire server.

Tested using the latest version of FlameCord AND Waterfall. Same results.

spark-report: https://spark.lucko.me/7qFFxV6Cnm
stacktrace: https://paste.gg/p/anonymous/c8e32b2e60794b3cb9fc330f90925ab4
console-log: https://paste.gg/p/anonymous/7f955d7652594dd6b0fa9bcaa52fd5b8

**Comment by Derkades** [comment]
Those error messages are normal if your website is not reachable, and should not cause any issues.

The spark report shows a few IO-related threads at 100% (floodgate netty worker, jetty webserver in plan plugin, OkHttp client in buycraft plugin, etc.). Nameless IO threads are at 0.60%.

I don't have enough experience looking at spark reports to say for sure, but it seems to be like this is not an issue with any of your plugins or Minecraft server software, but rather with system-level software or hardware. Anything IO-related is extremely slow.

**Comment by Whitescan** [comment]
Yeah I noticed this as well, but it's odd to me the console is only spammed with Nameless and also it's the only one with a stacktrace.
I gotta start somewhere. 
However, tests without Nameless proofed BuycraftX and Floodgate seem to also break. 

Unsure what to do but thanks for looking into this!
