### ISSUE TITLE
[BUG] Can't /register

### ISSUE THREAD

**Issue by StoreMaker** [NamelessMC/Nameless-Plugin#33]
### What kind of issue is it (Question, Bug, Suggestion, etc)?
Bug

### In which Minecraft Server Software did this occur?
Spigot, latest 1.10.2 version

### In which Build of NamelessMC Plugin did it occur?
Using the latest version of NamelessMC, deployed by Maven.

### How would you describe the issue?
I set up the API URL and everything seems to be fine, NamelessMC plugin loaded up but when I join the server, the plugin just throws errors (when nobody is on server, plugin is fine, doesn't throw any errors), also, /register command doesn't work.

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Yes, http://pastebin.com/fYrnypcr

**Comment by IsS127** [comment]
Fixed
