### ISSUE TITLE
Registration rewards

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless-Plugin#34]
(Copying across from [old repo](https://github.com/samerton/NamelessMC/issues/75)).

Allow configurable commands to execute once a user has successfully registered using /register (eg to reward the user with diamonds)

**Comment by samerton** [comment]
Now possible in v2 using https://namelessmc.com/resources/resource/15-namelessmc-websend/

**Comment by Derkades** [comment]
See #127
