### ISSUE TITLE
[Suggestion] Player Time Tracker

### ISSUE THREAD

**Issue by jonhoofficial** [NamelessMC/Nameless-Plugin#35]
A suggestion I have for NamelessMC is having an addon or something that can track player's play time on your Minecraft server and display the data on the NamelessMC website. Players will be able to see the top play times of the week or previous weeks and their own play times in their player profile or just by searching their name on the page.

**Comment by Derkades** [comment]
Will be possible with https://github.com/NamelessMC/Nameless/issues/738
