### ISSUE TITLE
Green checkmark emoji gets replaced with black and white version

### ISSUE THREAD

**Issue by JustJP2K** [NamelessMC/Nameless-Plugin#361]
The green checkmark emoji will be shown as black and white on pages.

**Comment by PadowYT2** [comment]
What do you mean with this issue? Can you screenshot?

**Comment by JustJP2K** [comment]
![image](https://github.com/NamelessMC/Nameless-Plugin/assets/74447960/363e5f4d-8136-4951-bd29-5ef56443313b)
![image](https://github.com/NamelessMC/Nameless-Plugin/assets/74447960/0976efb9-0172-400a-81e9-0f646317469c)

**Comment by PadowYT2** [comment]
Completly wrong repository, you are on the **plugin** repository. Also report to the template author

**Comment by JustJP2K** [comment]
> Completly wrong repository, you are on the **plugin** repository. Also report to the template author

Ah my bad sorry about wrong repo. also this also is the problem with default template
