### ISSUE TITLE
Group Sync

### ISSUE THREAD

**Issue by Spikey101** [NamelessMC/Nameless-Plugin#39]
Bug
NamelessMC 1.0.1.6 - Spigot 1.8.8 - Latest BungeeCord - LuckPerms - AuthmeReloaded
I setup group synchronisation with the namelessmc plugin and put the plugin in my bungeecord folder, set the api key in the config and enabled the plugin API. I created a group "testgroup" on the website which gave the ID 4, I went in the bungeecord plugins and edited the GroupSyncPermissions.yml and added 4: "web.testgroup" i then gave the permission "web.testgroup" to a user and when they registered on the forums they are still in the default group...
I have no errors in the bungeecord console.

**Comment by IsS127** [comment]
Group sync is when someone joins, I'll add this into register in the pre-2

**Comment by Spikey101** [comment]
Sorry for the confusion, but what do you mean it is when someone joins? So if someone joins my server as member I have 4: "member" which is given to the member group, but what if he buys rank upgrade to VIP and vip group has 5: "vip" would it put him into the VIP group on the website? From what I understand you mean that it only syncs the group 1 time?

**Comment by IsS127** [comment]
What i am saying is, group sync only works when someone joins the server. I dont mean new players or anything like that. I mean it checks the player permission when someone enters the server. Thats how it is at the moment. Later it will check for example every 5 min

And there is no way to check the permission if someone logins via the webiste.. The server interacts with the web api. the website doesnt interact with the server. But that isnt impossible though. Ill see what we can do. But dont expect this to be added in the first release of the plugin.

And that

**Comment by Tomw787** [comment]
Hi, I am having the same issue, I've tried syncing permissions and its not working. I've changed the permissions file and added the permission.

**Comment by Derkades** [comment]
Closing this since the next version will have a completely new system for group syncing (easier!)
