### ISSUE TITLE
The plugin throws a bunch of infinite repeating warns

### ISSUE THREAD

**Issue by TheJoshue** [NamelessMC/Nameless-Plugin#411]
Hello there

My setup:
- CarbonSpigot 1.8.8 [paid fork of paper-1.8.8 or tacospigot-1.8.8 (which is also fork of paper)]
- running using Java21
- NamelessPlugin 3.4.2 (i tried both Spigot and Paper version of the plugin, same thing for both except that Paper one does not load at all)

So what happens:
1. When i start server, NamelessPlugin says that it is loaded and enabled regularly...
2. When server is finally done with startup, NamelessPlugin throws this: https://mclo.gs/7kgGuIg
3. After some time of running server, there are no errors, so after few hours maybe NamelessPlugin starts to throw this on repeat for eternity (my log file from few hours is literally 9MBs) until i turn off the server: https://mclo.gs/1wGqZU8

Just to mention to be clear, these logs are when I tested using NamelessPlugin for spigot, not for paper, because for paper i see that it meant to be used for little bit higher MC versions than 1.8.8

**Comment by Derkades** [comment]
You are using the correct jar file. I don't really understand what's going on, but since it fails in the plugin class loader and we have not had any such issues reported with other servers, I suspect this is an issue with CarbonSpigot.

**Comment by TheJoshue** [comment]
> You are using the correct jar file. I don't really understand what's going on, but since it fails in the plugin class loader (not in Nameless-Plugin) and we have not had any such issues reported with other servers, I suspect this is an issue with CarbonSpigot.

Weirdly, this error did not happen and i restarted server more than 50 times for sure...

Thank you
