### ISSUE TITLE
An question

### ISSUE THREAD

**Issue by baxandrei** [NamelessMC/Nameless-Plugin#43]
Group sync and permissions work woth groupmanager or what are list of compatible permissions plugins?

**Comment by IsS127** [comment]
It works with any group plugin, just that they have the permission.
It could work with groupmanager, permissionsex etc.

**Comment by baxandrei** [comment]
And how i can settup this, have an setting in config?

**Comment by IsS127** [comment]
Permissions have to be set the following way, you need to check the groups' ids in your NamelessMC web setup and here you have to set the permissions like the example down here. If the player has permission which has been set down here, then the group in which the permission is set will be applied to the player if it's registered in the web. 
 Here is a example how a config should look like

```
permissions:
  # If the player has 'custom.permission', their group will be set to 0
  0: "custom.permission"
```

**Comment by baxandrei** [comment]
Thanx

**Comment by IsS127** [comment]
No problem!
