### ISSUE TITLE
Commands for plugin not working/also group sync not working.

### ISSUE THREAD

**Issue by loldylanrose** [NamelessMC/Nameless-Plugin#52]
I am running the latest version of spigot, and the latest version of the plugin and can't seem to get the commands or the group sync to work.
While trying to do the commands it just doesn't recognize that the commands even exist, below I've linked the config for the commands
https://imgur.com/a/wngrs

The rank sync doesn't work even though I've connected my server to the site. I'm not sure what I'm doing wrong here any help would be lovely!
https://imgur.com/a/LHcwt

**Comment by Derkades** [comment]
In the v1 plugin you can't have both one command with subcommands and individual commands. Disable one.

Your group sync should look like this:
6: nameless.donator

**Comment by loldylanrose** [comment]
Thanks so much, so this is how the group sync should look?
https://imgur.com/a/8DZjH

**Comment by Derkades** [comment]
Yes that should work, give your donators the nameless.donator permission

**Comment by loldylanrose** [comment]
Thanks, great plugin, thanks for the quick response!
