### ISSUE TITLE
Sponge Support

### ISSUE THREAD

**Issue by X00LA** [NamelessMC/Nameless-Plugin#53]
Is there a chance to get Sponge support in the future? It would be really nice to have thet because it would make things easier for a lot of server owners with Sponge, Sponge/Forge servers.
I tried to compile the Plugin for API version 6.0.0, but it end up with errors I can't fix by myself.
Support for Sponge 7.0.0 or 7.1.0 would be great!

Regards

**Comment by xeu100** [comment]
Send over error logs.

**Comment by VOrlando520** [comment]
I know this is over a year old, but is there any plans in continued sponge support? Love the software, would love to use it with my pixelmon server

**Comment by Derkades** [comment]
No one is working on a sponge version right now

**Comment by VOrlando520** [comment]
Ah thats a shame. Would love to use this software :\

**Comment by RawrUniversal** [comment]
Will this get added? It would be really nice.

**Comment by Derkades** [comment]
With v2, the plugin was rewritten with multi platform support in mind, so now it would be possible to port it to sponge. Still, I would do other software like Velocity first because of higher demand.

**Comment by Derkades** [comment]
Added for the next version
