### ISSUE TITLE
[BUG] colorcodes in LuckPerms Display name arent working

### ISSUE THREAD

**Issue by PixelNotFound** [NamelessMC/Nameless-Plugin#59]
In Luckperms you got a feature called Display name, this allowes you to set other names when you call vault for a users group name. But since the new group sync system of NamelessMC v2 uses the vault groupname instead of the permission system makes that my player base cant sync their groups anymore.

You can replicate this bug by giving a LP group a display name with color codes in it.

**Comment by Derkades** [comment]
It should work if you copy paste *exactly* what the plugin is sending: https://github.com/NamelessMC/Nameless-Plugin/wiki/v2:-Rank-sync#getting-rank-names-manually-for-online-players-only

**Comment by Derkades** [comment]
Otherwise, see #63
