### ISSUE TITLE
[Suggestion] Bungeecord support

### ISSUE THREAD

**Issue by PixelNotFound** [NamelessMC/Nameless-Plugin#60]
I would like to see this in bungeecord with all the same functions + That the bungeecord sends the current player amouth instead of the servers itself. Because only the bungeecord has internet access and the others dont for secuirity reasons.

**Comment by rukenantoni** [comment]
+1

**Comment by Derkades** [comment]
I don't think we are going to add bungeecord support, because it limits the features we can add. Someone else is welcome to, but I am not going to maintain two versions of the plugin
