### ISSUE TITLE
Error starting NamelessMC

### ISSUE THREAD

**Issue by SkippTekk** [NamelessMC/Nameless-Plugin#61]
Issue: Bug
Minecraft version: Craftbukkit Spigot 1.8.8
Minecraft Spigot API: 1.8.8-R0.1-SNAPSHOT
Namless version: NamelessSpigot beta 19

i couldn't do /validate on my non-OP account, and it didn't register the command. say's it's unknown. so i turned on Debug mode. rebooted my server. and got this. https://pastebin.com/w1JSQuJm 

Full log of server: https://pastebin.com/ngkhY1tu

Photo's https://gyazo.com/c9a430b4fa725dfa60d07af011405dd5

**Comment by Derkades** [comment]
Beta-19 is broken, please use beta-18

**Comment by SkippTekk** [comment]
alright, switching now.

**Comment by SkippTekk** [comment]
Alright i have changed and it works awesome. thanks man!
