### ISSUE TITLE
/notifications link has double http:// resulting in a random website on click

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless-Plugin#65]
### What kind of issue is it? (question, bug, suggestion, etc.)
Bug

### In which Minecraft Server Software did it occur, Spigot or BungeeCord?
Spigot

### In which version did it occur? 
Beta 27

### How would you describe the issue? 
When I make a report, and then do /notifications and click the link in chat, it opens a link "http://https://MYWEBSITE.com/user/alerts/?view=XXX

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
http://prntscr.com/nyn53d

**Comment by Derkades** [comment]
The plugin does not add http:// afaik, it might be a website issue

**Comment by Lmmb74** [comment]
It's also possible that you mistyped "http://" at the beginning of api-url in config.yml
