### ISSUE TITLE
Plugin Not working and spamming console.

### ISSUE THREAD

**Issue by Arlind-A** [NamelessMC/Nameless-Plugin#68]
The plugin is spamming my console with errors. Won't let me use any command related to the plugin. I've uninstalled it like 10 times now and changed the API like 10 times also and still the same results. Using the latest version of the plugin and using V2.0.0 Pre-6 website version.

ERROR:
> [14:59:17 WARN]: com.namelessmc.NamelessAPI.ApiError: An API error occured with error code 6
> [14:59:17 WARN]: at com.namelessmc.NamelessAPI.NamelessAPI.submitServerInfo(NamelessAPI.java:118)
> [14:59:17 WARN]: at com.namelessmc.plugin.spigot.ServerDataSender.lambda$1(ServerDataSender.java:78)
> [14:59:17 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [14:59:17 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [14:59:17 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [14:59:17 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [14:59:17 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by samerton** [comment]
Not sure what's happening here, but the following are reasons why the API would be returning an error code 6:

- post request is empty or the object isn't named 'info'
- server-id, max-memory, free-memory, allocated-memory, tps, players aren't set

Is this something you've seen before @Derkades?

**Comment by Derkades** [comment]
The plugin always sends the parameter with the correct json, so it is probably a friendly url issue. Change the API URL to this format `yoursite.com/index.php?route=/api/v2/API_KEY`
