### ISSUE TITLE
Compiled builds?

### ISSUE THREAD

**Issue by Fiiily** [NamelessMC/Nameless-Plugin#7]
Do you have some jars for me to use or a build server?

**Comment by Lmmb74** [comment]
I just made a pull request where I add maven support. Check my fork. You will only have to install Maven in your pc and execute a command. But I uploaded a jar here: https://drive.google.com/file/d/0B6YspTAL_CB_UWhTaW94QlZIMWc/view?usp=sharing

**Comment by Lmmb74** [comment]
Answer if it helped you pls

**Comment by Fiiily** [comment]
404

**Comment by Lmmb74** [comment]
lol, gonna upload it again now

**Comment by Lmmb74** [comment]
https://drive.google.com/open?id=0B6YspTAL_CB_TTAwQlV4TExWdnM

**Comment by Lmmb74** [comment]
Close this. The maven update has been succesfully pushed.

**Comment by Lmmb74** [comment]
@samerton, close this.

**Comment by samerton** [comment]
There is now a Jenkins build server available, you can find the first available jar file [here](http://ci.namelessmc.com:8080/job/Nameless-Plugin/lastBuild/com.namelessmc$Nameless/). Please note that the plugin is still in development, and is not yet ready for use on a public server.
