### ISSUE TITLE
/validate is not working

### ISSUE THREAD

**Issue by DinkSpider** [NamelessMC/Nameless-Plugin#70]
# Template,
* What kind of issue is it? bug
* In which Minecraft Server Software did it occur, Spigot
* In which version did it occur? 1.8.8 Minecraft Version. Nameless Plugin for v2 beta-29
* How would you describe the issue? 
When a player register in the website, it doesn't ask them to do /validate (numbers) in the server.
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
no
# PLEASE UPLOAD IMAGES TO IMGUR OR ANY OTHER IMAGE UPLOADER WEBSITE!
# PLEASE UPLOAD LOGS TO HASTEBIN.COM!

### What kind of issue is it? (question, bug, suggestion, etc.)
Bug

### In which Minecraft Server Software did this occur?
Spigot

### In which version did it occur?
Nameless Plugin for v2 beta-29

### How would you describe the issue?
Command /validate not working

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
No

**Comment by Derkades** [comment]
More information please. Does the command throw an error when it is run?

**Comment by DinkSpider** [comment]
So, when a player register in the website, it never asks to do /validate (numbers) in game. It just says the account has been validated.

**Comment by Derkades** [comment]
That's an issue on the website end. Either it's a bug or the option to skip verification is still enabled. The best way to get help with this is through discord or the discussion section on spigot

**Comment by DinkSpider** [comment]
Tried discord, all helpers ignored me, welp.....k then

**Comment by DinkSpider** [comment]
Been 3 days asking for help in discord smh

**Comment by Derkades** [comment]
https://github.com/NamelessMC/Nameless/issues/1577
