### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Jager67** [NamelessMC/Nameless-Plugin#71]
* What kind of issue is it? 
Bug
* In which Minecraft Server Software did it occur, Spigot or BungeeCord?
BungeeCord and PaperSpigot
* In which version did it occur? If it's a jenkins build, tell us the build number.
Beta 29
* How would you describe the issue? 
At first the API wasn't connecting then fix the link in the config.yml to not display the http:// then once that was fixed I tried everything to get any commands to work but nothing not even the /nlpl reload works 
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
https://imgur.com/a/CTuFyXK

**Comment by Jager67** [comment]
Heres what spamming my console.
https://imgur.com/a/NdjnzDj

**Comment by Derkades** [comment]
Please follow the instructions here: https://github.com/NamelessMC/Nameless/wiki/Plugin-is-not-working
