### ISSUE TITLE
Validate 

### ISSUE THREAD

**Issue by EchoRapidz** [NamelessMC/Nameless-Plugin#72]
* Question
* The Official NamelessMC plugin
* Nameless V2
* Paper 1.14.4
* How do i make it so when api is enabled it doesn't just activate accounts by itself. I want players to have to type the /validate (code) into there account. Just dont want it to be easy for a player to impersonate another player.
Thanks, Rapidz

**Comment by Derkades** [comment]
See https://github.com/NamelessMC/Nameless/issues/1577
