### ISSUE TITLE
Error is being thrown on startup

### ISSUE THREAD

**Issue by eirikh1996** [NamelessMC/Nameless-Plugin#73]
# Template,
###What kind of issue is it? (question, bug, suggestion, etc.)
Bug
###In which Minecraft Server Software did it occur, Spigot or BungeeCord?
PaperMC
###In which version did it occur? If it's a jenkins build, tell us the build number.
1.14.4
###How would you describe the issue? 
When I start the server, I get this error in console: Error occured while enabling NamelessPlugin-vbeta29 (is it up to date?) I have linked it to a page using Nameless and has Vault installed
###Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Stacktrace: https://pastebin.com/cWb9H7s0

**Comment by Derkades** [comment]
Make sure to update to the latest version. To fix your issue, please read this wiki page: https://github.com/NamelessMC/Nameless/wiki/Plugin-is-not-working
