### ISSUE TITLE
Plugin NamelessMC vbeta-31 generated an exception while executing task ##

### ISSUE THREAD

**Issue by eirikh1996** [NamelessMC/Nameless-Plugin#74]
### What kind of issue is it? (question, bug, suggestion, etc.)
Bug
### In which Minecraft Server Software did it occur, Spigot or BungeeCord?
PaperMC
### In which version did it occur? If it's a jenkins build, tell us the build number.
1.14.4
### How would you describe the issue? 
A scheduled task keep generating exceptions, printing out a stacktrace in console every 10 seconds
### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
https://pastebin.com/BQCtyZR9

**Comment by samerton** [comment]
Could you have a look at [this page](https://github.com/NamelessMC/Nameless/wiki/Plugin-is-not-working)? The suggestions on there have fixed all cases of this error so far.

**Comment by eirikh1996** [comment]
Not in my case

**Comment by Derkades** [comment]
It is definitely one of the issues on that page
