### ISSUE TITLE
Nameless-Plugin Does Not Recognise Permissions nor Economy

### ISSUE THREAD

**Issue by A248** [NamelessMC/Nameless-Plugin#76]
### What kind of issue is it? (question, bug, suggestion, etc.)
Bug

### In which Minecraft Server Software did this occur?
Spigot, specifically git-PaperSpigot-"4c7641d" (MC: 1.8.8)

### In which version did it occur?
beta-31

### How would you describe the issue?
Vault is loaded and enabled, other plugins are able to successfully hook into Vault. PEX hooks with Vault. SaneEconomy, an economy plugin, also hooks into Vault. **Yet, Nameless-Plugin does not hook into Vault.**

Plugin versions:
* Using Vault 1.5.6-b49
* Using SaneEconomy 0.13.1-SNAPSHOT
* Using PermissionsEx 1.23.4

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Server log demonstrates that Vault, PEX, and SaneEconomy all function fine, but Nameless-Plugin does not hook with any of them.
https://pastebin.com/u82SEK7G

**Comment by Derkades** [comment]
Hopefully fixed in beta-32

**Comment by A248** [comment]
https://github.com/NamelessMC/Nameless-Plugin/commit/215473dbaaca584d733acffb6946fc17d2a66ba6 should fix it. I don't know why you are messing around with onLoad, but it doesn't matter.
