### ISSUE TITLE
Wordpress Sync

### ISSUE THREAD

**Issue by FrozenBeard** [NamelessMC/Nameless-Plugin#77]
Is there a possibility of having a fork of this plugin to work with wordpress registered users?
Its the biggest CMS that exists and there isn't a working solution to let people in-game sync their Minecraft account (verified) to wordpress CMS registered user.

I understand this is out of the scope of your current project, but this would be a much larger case scenario with the scale of wordpress plugins and themes that exist.

**Comment by Derkades** [comment]
Yeah, that would be out of scope for this project. There is no abstraction layer in the plugin that would allow it to work with other CMS software. I think it's a better idea to create a new plugin to do this.
