### ISSUE TITLE
Sending Placeholders to Website

### ISSUE THREAD

**Issue by haohaostudio** [NamelessMC/Nameless-Plugin#83]
# Sending Placeholders to Website

### What kind of issue is it? (question, bug, suggestion, etc.)
Suggestion

### In which version did it occur?
Pre release 1

### How would you describe the issue?
Like the way it sent before:
We can set what to send and where to show on a nameless-website
We can show some placeholders on a website

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
NO

**Comment by samerton** [comment]
The plugin already sends over Placeholder API placeholders, currently waiting on https://github.com/NamelessMC/Nameless/issues/1484 (on the website side) to display them.
