### ISSUE TITLE
Suggestion | Anti-Spam - Report cooldown

### ISSUE THREAD

**Issue by StormyIceLeopard** [NamelessMC/Nameless-Plugin#84]
This feature could really help prevent abuse/spam of /report.

I would like to see a cooldown feature for when players report players.
Like if Alex does `/report Steve Fly` he is not able to do it again, or at least for a duration of time.
But still allows Alex to do `/report Notch XRAY`

Basically not a cooldown on the command itself, but rather a cooldown on the one being reported.

**Comment by Derkades** [comment]
Wouldn't a global cooldown be better? By reporting different users every time players can still spam moderators with reports. There can be legitimate reasons for reporting a player multiple times, for example if you see them breaking more rules. Or maybe both: a cooldown for reports in general, and a longer cooldown for reporting a specific user
