### ISSUE TITLE
v1.16.1 server support

### ISSUE THREAD

**Issue by ZandercraftGames** [NamelessMC/Nameless-Plugin#94]
### What kind of issue is it? (question, bug, suggestion, etc.)
Bug

### In which Minecraft Server Software did this occur?
PaperMC

### In which version did it occur?
Minecraft: 1.16.1
NamelessMC: 2.0 Pre-7

### How would you describe the issue?
Many commands including /register result in an error.

### Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
Yes, [https://hastebin.com/qocikakawo.php](https://hastebin.com/qocikakawo.php)

**Comment by Derkades** [comment]
Please check for console errors at startup, it looks like the plugin hasn't loaded properly

**Comment by ZandercraftGames** [comment]
Startup occurs as follows:
```
[06:50:54 WARN]: Legacy plugin NamelessMC vbeta-32 does not specify an api-version.
```
General error, but would be good practice to specify an API version even though this doesn't cause issues.
Then:
```
[06:50:56 INFO]: [NamelessMC] Loading NamelessMC vbeta-32
...
[06:51:18 INFO]: [NamelessMC] Enabling NamelessMC vbeta-32*
```
Nothing else.

**Comment by Derkades** [comment]
You might have missed the error, the API failed to initialize hence the NullPointerExceptions later. Ideally the plugin should refuse to load at all in this case, I need to fix this.

Common problems are listed here: https://github.com/NamelessMC/Nameless/wiki/Plugin-is-not-working

**Comment by ZandercraftGames** [comment]
Ive gone through the entirety of the startup to look for errors and have found none. What class/package name should I be looking for, as searching for "nameless" finds only what I gave you.

If you were referring to this (`[06:50:54 WARN]: Legacy plugin NamelessMC vbeta-32 does not specify an api-version.`) meaning that the API failed to initialize, that is a common Paper error. If you were referring to the namelessmc-side API, then I'm not sure what would be causing it.

**Comment by Derkades** [comment]
Are you in the discord server - can you DM your latest.log file? Otherwise you can email it to robin@derkad.es as well

**Comment by ZandercraftGames** [comment]
Im in the discord. I will send that to you ASAP.

**Comment by artificialai223** [comment]
I am fine, im running it on 1.16.2

**Comment by Derkades** [comment]
Yeah, the title is somewhat misleading, this issue has nothing to do with specific Minecraft versions
